import "./globals.css";
import "aos/dist/aos.css";
import AosHook from "@/utils/AosHook";
import AdminContextProvider from "@/Context/AdminContext";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AdminContextProvider>
          <AosHook>{children}</AosHook>
        </AdminContextProvider>
        <Toaster position="bottom-center" />
      </body>
    </html>
  );
}
